const DNP_CATALOG_VERSION = 1;

const DNP_AREAS = [
  { id: 'social', label: 'Sociais/Emocionais', shortLabel: 'Sociais' },
  { id: 'language', label: 'Linguagem/Comunicação', shortLabel: 'Linguagem' },
  { id: 'cognitive', label: 'Cognitivos — aprender, pensar e resolver problemas', shortLabel: 'Cognitivos' },
  { id: 'movement', label: 'Movimento/Desenvolvimento Físico', shortLabel: 'Movimento' }
];

const DNP_STAGES = [
  { id: '2m', months: 2, label: '2 meses', childWord: 'bebê' },
  { id: '4m', months: 4, label: '4 meses', childWord: 'bebê' },
  { id: '6m', months: 6, label: '6 meses', childWord: 'bebê' },
  { id: '9m', months: 9, label: '9 meses', childWord: 'bebê' },
  { id: '12m', months: 12, label: '12 meses', childWord: 'bebê' },
  { id: '15m', months: 15, label: '15 meses', childWord: 'filho' },
  { id: '18m', months: 18, label: '18 meses', childWord: 'filho' },
  { id: '24m', months: 24, label: '2 anos', childWord: 'filho' },
  { id: '30m', months: 30, label: '30 meses', childWord: 'filho' },
  { id: '36m', months: 36, label: '3 anos', childWord: 'filho' },
  { id: '48m', months: 48, label: '4 anos', childWord: 'filho' },
  { id: '60m', months: 60, label: '5 anos', childWord: 'filho' }
];

const DNP_EXPECTED_COUNTS = {
  '2m': 11, '4m': 13, '6m': 12, '9m': 13, '12m': 10, '15m': 13,
  '18m': 15, '24m': 13, '30m': 15, '36m': 12, '48m': 17, '60m': 15
};

const DNP_STATUS = {
  does: { id: 'does', label: 'Já faz' },
  starting: { id: 'starting', label: 'Está começando / faz às vezes' },
  not_yet: { id: 'not_yet', label: 'Ainda não faz' },
  unknown: { id: 'unknown', label: 'Não sei / não tive oportunidade de observar' }
};

function dnpMilestone(stageId, areaId, order, text, example = '', flags = []) {
  return {
    id: `${stageId}-${areaId}-${String(order).padStart(2, '0')}`,
    stageId,
    areaId,
    order,
    text,
    example,
    flags
  };
}

function dnpActivity(stageId, order, group, title, text, flags = []) {
  return {
    id: `${stageId}-act-${String(order).padStart(2, '0')}`,
    stageId,
    order,
    group,
    title,
    text,
    flags
  };
}

const DNP_MILESTONES = [
  dnpMilestone('2m', 'social', 1, 'Acalma-se quando a família conversa ou o pega no colo.'),
  dnpMilestone('2m', 'social', 2, 'Olha para o rosto de quem está perto.'),
  dnpMilestone('2m', 'social', 3, 'Parece feliz ao ver alguém se aproximar.'),
  dnpMilestone('2m', 'social', 4, 'Sorri quando alguém fala ou sorri para ele.'),
  dnpMilestone('2m', 'language', 1, 'Emite sons que não são choro.'),
  dnpMilestone('2m', 'language', 2, 'Reage a sons altos.'),
  dnpMilestone('2m', 'cognitive', 1, 'Acompanha com o olhar quem se move perto dele.'),
  dnpMilestone('2m', 'cognitive', 2, 'Olha para um brinquedo por alguns segundos.'),
  dnpMilestone('2m', 'movement', 1, 'Mantém a cabeça erguida quando está de bruços.'),
  dnpMilestone('2m', 'movement', 2, 'Move os dois braços e as duas pernas.'),
  dnpMilestone('2m', 'movement', 3, 'Abre as mãos por alguns instantes.'),

  dnpMilestone('4m', 'social', 1, 'Sorri sozinho para chamar a atenção da família.'),
  dnpMilestone('4m', 'social', 2, 'Dá risadinha (ainda sem uma gargalhada completa) quando alguém tenta fazê-lo rir.'),
  dnpMilestone('4m', 'social', 3, 'Olha, se mexe ou emite sons para conseguir ou manter a atenção de alguém.'),
  dnpMilestone('4m', 'language', 1, 'Faz sons como “oooo” e “aahh”.'),
  dnpMilestone('4m', 'language', 2, 'Responde com sons quando alguém fala com ele.'),
  dnpMilestone('4m', 'language', 3, 'Vira a cabeça na direção da voz.'),
  dnpMilestone('4m', 'cognitive', 1, 'Se está com fome, abre a boca ao ver o peito ou a mamadeira.'),
  dnpMilestone('4m', 'cognitive', 2, 'Olha para as próprias mãos com interesse.'),
  dnpMilestone('4m', 'movement', 1, 'Mantém a cabeça firme, sem apoio, quando está no colo.'),
  dnpMilestone('4m', 'movement', 2, 'Segura um brinquedo colocado na mão.'),
  dnpMilestone('4m', 'movement', 3, 'Balança os braços em direção aos brinquedos.'),
  dnpMilestone('4m', 'movement', 4, 'Leva as mãos à boca.'),
  dnpMilestone('4m', 'movement', 5, 'De bruços, empurra o tronco para cima apoiado nos cotovelos ou antebraços.'),

  dnpMilestone('6m', 'social', 1, 'Reconhece pessoas familiares.'),
  dnpMilestone('6m', 'social', 2, 'Gosta de se olhar no espelho.'),
  dnpMilestone('6m', 'social', 3, 'Dá risadas.'),
  dnpMilestone('6m', 'language', 1, 'Se reveza fazendo sons com a família.'),
  dnpMilestone('6m', 'language', 2, 'Sopra saliva, colocando a língua para fora.'),
  dnpMilestone('6m', 'language', 3, 'Faz gritinhos ou outros sons agudos.'),
  dnpMilestone('6m', 'cognitive', 1, 'Leva objetos à boca para explorá-los.'),
  dnpMilestone('6m', 'cognitive', 2, 'Estica o braço para pegar um brinquedo que deseja.'),
  dnpMilestone('6m', 'cognitive', 3, 'Fecha os lábios para mostrar que não quer mais comida.'),
  dnpMilestone('6m', 'movement', 1, 'Vira de barriga para baixo para barriga para cima.', 'Direção conforme o CDC atual (de prono para supino). A cartilha em português traz a direção inversa.', ['cdc-roll-correction']),
  dnpMilestone('6m', 'movement', 2, 'De bruços, empurra o corpo com os braços esticados.'),
  dnpMilestone('6m', 'movement', 3, 'Apoia-se nas mãos para se sustentar quando está sentado.'),

  dnpMilestone('9m', 'social', 1, 'Fica tímido, “grudado” ou com receio perto de pessoas desconhecidas.'),
  dnpMilestone('9m', 'social', 2, 'Mostra várias expressões no rosto, como alegria, tristeza, raiva e surpresa.'),
  dnpMilestone('9m', 'social', 3, 'Olha quando é chamado pelo nome.'),
  dnpMilestone('9m', 'social', 4, 'Reage quando a família sai: olha, estende o braço ou chora.'),
  dnpMilestone('9m', 'social', 5, 'Sorri ou ri na brincadeira de esconde-achou.'),
  dnpMilestone('9m', 'language', 1, 'Faz sons repetidos diferentes, como “mamamama” e “babababa”.'),
  dnpMilestone('9m', 'language', 2, 'Levanta os braços para ser pego no colo.'),
  dnpMilestone('9m', 'cognitive', 1, 'Procura um objeto que caiu e saiu do campo de visão, como a colher ou um brinquedo.'),
  dnpMilestone('9m', 'cognitive', 2, 'Bate duas coisas uma na outra.'),
  dnpMilestone('9m', 'movement', 1, 'Chega sozinho à posição sentada.'),
  dnpMilestone('9m', 'movement', 2, 'Passa um objeto de uma mão para a outra.'),
  dnpMilestone('9m', 'movement', 3, 'Usa os dedos para “puxar” a comida em direção a si.'),
  dnpMilestone('9m', 'movement', 4, 'Senta sem apoio.'),

  dnpMilestone('12m', 'social', 1, 'Brinca com a família em jogos simples, como bater palminhas.'),
  dnpMilestone('12m', 'language', 1, 'Acena “tchau”.'),
  dnpMilestone('12m', 'language', 2, 'Chama um cuidador de “mamãe”, “papai” ou outro nome especial.'),
  dnpMilestone('12m', 'language', 3, 'Entende “não”: pausa ou para por um momento quando ouve a palavra.'),
  dnpMilestone('12m', 'cognitive', 1, 'Coloca algo em um recipiente, como um bloco em um copo.'),
  dnpMilestone('12m', 'cognitive', 2, 'Procura um objeto que viu alguém esconder, como um brinquedo debaixo de um pano.'),
  dnpMilestone('12m', 'movement', 1, 'Puxa-se para ficar de pé.'),
  dnpMilestone('12m', 'movement', 2, 'Anda se segurando nos móveis.'),
  dnpMilestone('12m', 'movement', 3, 'Bebe de um copo sem tampa enquanto um adulto o segura.'),
  dnpMilestone('12m', 'movement', 4, 'Pega objetos pequenos entre o polegar e o indicador, como pedacinhos de comida.'),

  dnpMilestone('15m', 'social', 1, 'Imita outra criança na brincadeira, como tirar brinquedos de um pote quando a outra faz isso.'),
  dnpMilestone('15m', 'social', 2, 'Mostra um objeto de que gosta.'),
  dnpMilestone('15m', 'social', 3, 'Bate palmas quando está animado.'),
  dnpMilestone('15m', 'social', 4, 'Abraça um bicho de pelúcia ou outro brinquedo.'),
  dnpMilestone('15m', 'social', 5, 'Demonstra carinho: abraça, aconchega ou beija.'),
  dnpMilestone('15m', 'language', 1, 'Tenta dizer uma ou duas palavras além de “mamãe” e “papai”, como “bo” para bola.'),
  dnpMilestone('15m', 'language', 2, 'Olha para um objeto conhecido quando alguém o nomeia.'),
  dnpMilestone('15m', 'language', 3, 'Segue um pedido feito com gesto e palavras, como entregar o brinquedo quando a mão é estendida e alguém diz “me dá”.'),
  dnpMilestone('15m', 'language', 4, 'Aponta para pedir algo ou para pedir ajuda.'),
  dnpMilestone('15m', 'cognitive', 1, 'Tenta usar objetos do jeito certo, como telefone, copo ou livro.'),
  dnpMilestone('15m', 'cognitive', 2, 'Empilha pelo menos dois objetos pequenos, como blocos.'),
  dnpMilestone('15m', 'movement', 1, 'Dá alguns passos sozinho.'),
  dnpMilestone('15m', 'movement', 2, 'Usa os dedos para levar um pouco de comida à boca.'),

  dnpMilestone('18m', 'social', 1, 'Afasta-se um pouco, mas olha para ter certeza de que a família continua por perto.'),
  dnpMilestone('18m', 'social', 2, 'Aponta para mostrar algo interessante.'),
  dnpMilestone('18m', 'social', 3, 'Estende as mãos para que alguém as lave.'),
  dnpMilestone('18m', 'social', 4, 'Olha algumas páginas de um livro junto com a família.'),
  dnpMilestone('18m', 'social', 5, 'Ajuda a se vestir, enfiando o braço na manga ou levantando o pé.'),
  dnpMilestone('18m', 'language', 1, 'Tenta dizer três ou mais palavras além de “mamãe” e “papai”.'),
  dnpMilestone('18m', 'language', 2, 'Segue um pedido de um passo sem gestos, como entregar o brinquedo quando ouve “me dá”.'),
  dnpMilestone('18m', 'cognitive', 1, 'Imita tarefas da casa, como varrer.'),
  dnpMilestone('18m', 'cognitive', 2, 'Brinca de um jeito simples, como empurrar um carrinho.'),
  dnpMilestone('18m', 'movement', 1, 'Anda sem se segurar em ninguém nem em nada.'),
  dnpMilestone('18m', 'movement', 2, 'Rabisca.'),
  dnpMilestone('18m', 'movement', 3, 'Bebe de um copo sem tampa e às vezes derrama.'),
  dnpMilestone('18m', 'movement', 4, 'Come com os dedos.'),
  dnpMilestone('18m', 'movement', 5, 'Tenta usar a colher.'),
  dnpMilestone('18m', 'movement', 6, 'Sobe e desce de um sofá ou cadeira sem ajuda.'),

  dnpMilestone('24m', 'social', 1, 'Percebe quando alguém está magoado ou chateado, por exemplo parando ou ficando sério se a pessoa chora.'),
  dnpMilestone('24m', 'social', 2, 'Olha o rosto da família para saber como reagir em uma situação nova.'),
  dnpMilestone('24m', 'language', 1, 'Aponta para figuras do livro quando perguntam, por exemplo “onde está o urso?”.'),
  dnpMilestone('24m', 'language', 2, 'Junta pelo menos duas palavras, como “mais leite”.'),
  dnpMilestone('24m', 'language', 3, 'Aponta para pelo menos duas partes do corpo quando pedem para mostrar.'),
  dnpMilestone('24m', 'language', 4, 'Usa gestos além de acenar e apontar, como mandar beijo ou balançar a cabeça para “sim”.'),
  dnpMilestone('24m', 'cognitive', 1, 'Segura um objeto com uma mão e usa a outra, por exemplo segura o pote e tira a tampa.'),
  dnpMilestone('24m', 'cognitive', 2, 'Tenta usar interruptores, botões ou travas de um brinquedo.'),
  dnpMilestone('24m', 'cognitive', 3, 'Brinca com mais de um brinquedo ao mesmo tempo, como colocar comidinha em um pratinho.'),
  dnpMilestone('24m', 'movement', 1, 'Chuta uma bola.'),
  dnpMilestone('24m', 'movement', 2, 'Corre.'),
  dnpMilestone('24m', 'movement', 3, 'Sobe alguns degraus andando, com ou sem ajuda, sem precisar escalar.'),
  dnpMilestone('24m', 'movement', 4, 'Come com colher.'),

  dnpMilestone('30m', 'social', 1, 'Brinca ao lado de outras crianças e, às vezes, junto com elas.'),
  dnpMilestone('30m', 'social', 2, 'Mostra o que sabe fazer dizendo algo como “olha eu!”.'),
  dnpMilestone('30m', 'social', 3, 'Segue uma rotina simples quando pedem, como guardar brinquedos na hora de arrumar.'),
  dnpMilestone('30m', 'language', 1, 'Fala cerca de 50 palavras.'),
  dnpMilestone('30m', 'language', 2, 'Junta duas ou mais palavras incluindo uma ação, como “cachorro corre”.'),
  dnpMilestone('30m', 'language', 3, 'Nomeia figuras do livro quando apontam e perguntam “o que é isso?”.'),
  dnpMilestone('30m', 'language', 4, 'Usa palavras como “eu”, “mim” ou “nós”.'),
  dnpMilestone('30m', 'cognitive', 1, 'Usa objetos no faz de conta, como “alimentar” uma boneca com um bloco.'),
  dnpMilestone('30m', 'cognitive', 2, 'Resolve um problema simples, como subir em um banquinho baixo para alcançar algo.'),
  dnpMilestone('30m', 'cognitive', 3, 'Segue um pedido de dois passos, como “coloque o brinquedo no chão e feche a porta”.'),
  dnpMilestone('30m', 'cognitive', 4, 'Mostra que reconhece pelo menos uma cor, por exemplo apontando o lápis vermelho quando perguntam “qual é o vermelho?”.'),
  dnpMilestone('30m', 'movement', 1, 'Usa as mãos para torcer, como girar maçaneta ou destampar.'),
  dnpMilestone('30m', 'movement', 2, 'Tira sozinho algumas roupas, como calça folgada ou jaqueta aberta.'),
  dnpMilestone('30m', 'movement', 3, 'Pula no lugar com os dois pés.'),
  dnpMilestone('30m', 'movement', 4, 'Vira as páginas do livro uma a uma quando leem juntos.'),

  dnpMilestone('36m', 'social', 1, 'Acalma-se em cerca de 10 minutos depois que a família o deixa, por exemplo na entrada da creche.'),
  dnpMilestone('36m', 'social', 2, 'Repara em outras crianças e se junta a elas para brincar.'),
  dnpMilestone('36m', 'language', 1, 'Conversa com pelo menos duas trocas de turno.'),
  dnpMilestone('36m', 'language', 2, 'Faz perguntas de “quem”, “o que”, “onde” ou “por que”, como “onde está a mamãe?”.'),
  dnpMilestone('36m', 'language', 3, 'Diz qual ação aparece em uma figura ou no livro, como “correndo” ou “comendo”.'),
  dnpMilestone('36m', 'language', 4, 'Diz o próprio primeiro nome quando perguntam.'),
  dnpMilestone('36m', 'language', 5, 'Fala de um jeito que outras pessoas entendem na maior parte do tempo.'),
  dnpMilestone('36m', 'cognitive', 1, 'Desenha um círculo depois de ver alguém fazer.'),
  dnpMilestone('36m', 'cognitive', 2, 'Evita tocar em algo quente, como o fogão, quando a família avisa.'),
  dnpMilestone('36m', 'movement', 1, 'Passa peças grandes por um cordão, com supervisão.', 'Use contas grandes, macarrão grande ou argolas adequadas à idade. Evite peças pequenas. Permaneça ao lado o tempo todo.', ['safety-stringing']),
  dnpMilestone('36m', 'movement', 2, 'Veste sozinho algumas peças, como calça folgada ou jaqueta.'),
  dnpMilestone('36m', 'movement', 3, 'Usa o garfo.'),

  dnpMilestone('48m', 'social', 1, 'Finge ser outra pessoa ou personagem na brincadeira, como professor, herói ou cachorro.'),
  dnpMilestone('48m', 'social', 2, 'Pede para brincar com outras crianças quando ninguém está por perto, como “posso brincar com o Alex?”.'),
  dnpMilestone('48m', 'social', 3, 'Consola quem está magoado ou triste, por exemplo abraçando um amigo que chora.'),
  dnpMilestone('48m', 'social', 4, 'Evita perigos evidentes, como não pular de uma altura alta no parquinho.'),
  dnpMilestone('48m', 'social', 5, 'Gosta de ser “ajudante”.'),
  dnpMilestone('48m', 'social', 6, 'Muda o comportamento conforme o lugar, como biblioteca, parquinho ou espaço de culto.'),
  dnpMilestone('48m', 'language', 1, 'Fala frases com quatro ou mais palavras.'),
  dnpMilestone('48m', 'language', 2, 'Repete algumas palavras de uma música, história ou parlenda.'),
  dnpMilestone('48m', 'language', 3, 'Conta pelo menos uma coisa que aconteceu no dia, como “eu joguei bola”.'),
  dnpMilestone('48m', 'language', 4, 'Responde perguntas simples, como “para que serve o casaco?”.'),
  dnpMilestone('48m', 'cognitive', 1, 'Nomeia algumas cores de objetos.'),
  dnpMilestone('48m', 'cognitive', 2, 'Diz o que vem a seguir em uma história bem conhecida.'),
  dnpMilestone('48m', 'cognitive', 3, 'Desenha uma pessoa com três ou mais partes do corpo.'),
  dnpMilestone('48m', 'movement', 1, 'Pega uma bola grande na maior parte das vezes.'),
  dnpMilestone('48m', 'movement', 2, 'Serve a própria comida ou coloca água no copo, com um adulto por perto.'),
  dnpMilestone('48m', 'movement', 3, 'Desabotoa alguns botões.'),
  dnpMilestone('48m', 'movement', 4, 'Segura o lápis ou giz de cera entre os dedos e o polegar, sem fechar o punho.'),

  dnpMilestone('60m', 'social', 1, 'Segue regras ou espera a vez ao brincar com outras crianças.'),
  dnpMilestone('60m', 'social', 2, 'Canta, dança ou representa para a família.'),
  dnpMilestone('60m', 'social', 3, 'Faz tarefas simples em casa, como juntar pares de meia ou ajudar a limpar a mesa.'),
  dnpMilestone('60m', 'language', 1, 'Conta uma história ouvida ou inventada com pelo menos dois acontecimentos.'),
  dnpMilestone('60m', 'language', 2, 'Responde perguntas simples sobre um livro ou uma história.'),
  dnpMilestone('60m', 'language', 3, 'Mantém uma conversa com mais de três trocas de turno.'),
  dnpMilestone('60m', 'language', 4, 'Usa ou reconhece rimas simples, como gato/pato.'),
  dnpMilestone('60m', 'cognitive', 1, 'Conta até 10.'),
  dnpMilestone('60m', 'cognitive', 2, 'Nomeia alguns números de 1 a 5 quando alguém aponta para eles.'),
  dnpMilestone('60m', 'cognitive', 3, 'Usa palavras de tempo, como “ontem”, “amanhã”, “de manhã” ou “de noite”.'),
  dnpMilestone('60m', 'cognitive', 4, 'Presta atenção por cerca de 5 a 10 minutos em uma atividade, como história ou artesanato. Tempo de tela não conta.'),
  dnpMilestone('60m', 'cognitive', 5, 'Escreve algumas letras do próprio nome.'),
  dnpMilestone('60m', 'cognitive', 6, 'Nomeia algumas letras quando alguém aponta para elas.'),
  dnpMilestone('60m', 'movement', 1, 'Abotoa alguns botões.'),
  dnpMilestone('60m', 'movement', 2, 'Pula em um pé só.')
];

const DNP_ACTIVITIES = [
  dnpActivity('2m', 1, 'interacao', 'Responda aos sons do bebê', 'Quando ele emitir um som, sorria, fale e responda com entusiasmo. Essa troca ensina o vai-e-vem da conversa.'),
  dnpActivity('2m', 2, 'interacao', 'Converse, leia e cante', 'Fale, leia e cante perto do bebê. Isso ajuda a linguagem a se formar desde cedo.'),
  dnpActivity('2m', 3, 'interacao', 'Aconchego no colo', 'Segure e abrace o bebê com frequência. Responder a ele não o “estraga”; ajuda a se sentir seguro.'),
  dnpActivity('2m', 4, 'telas', 'Menos tela, mais presença', 'Quando estiver com o bebê, tente reduzir o próprio tempo de tela para perceber melhor os sinais dele.'),
  dnpActivity('2m', 5, 'rotina', 'Cuide também de quem cuida', 'Descansar e pedir ajuda torna mais fácil aproveitar esse começo.'),
  dnpActivity('2m', 6, 'interacao', 'Leia os sinais do bebê', 'Observe se ele quer brincar — sons e olhar — ou se precisa de pausa, como virar o rosto, bocejar ou ficar inquieto.'),
  dnpActivity('2m', 7, 'movimento', 'Tempo de bruços com supervisão', 'Com o bebê acordado, deite-o de bruços e coloque um brinquedo na altura dos olhos. Não o deixe sozinho. Se parecer sonolento, coloque-o de costas em local seguro para dormir.', ['sleep-safety']),
  dnpActivity('2m', 8, 'alimentacao', 'Só leite nesta fase', 'Até cerca de 6 meses, o bebê se alimenta de leite materno ou, quando a amamentação não for possível, de fórmula. Água, sucos e outros alimentos ainda não são adequados.', ['feeding-review']),
  dnpActivity('2m', 9, 'alimentacao', 'Sinais de fome e de saciedade', 'Mãos na boca, virar-se para o peito ou mamadeira e estalar os lábios podem indicar fome. Fechar a boca ou virar o rosto pode indicar que já basta.'),
  dnpActivity('2m', 10, 'seguranca', 'Nunca sacuda o bebê', 'Se o choro deixar alguém no limite, coloque o bebê em um lugar seguro e afaste-se por alguns minutos, voltando a olhar de 5 a 10 minutos. Sacudir pode causar lesão grave.', ['never-shake']),
  dnpActivity('2m', 11, 'rotina', 'Rotinas de sono e de alimentação', 'Horários parecidos ajudam o bebê a começar a entender o que vem a seguir.'),

  dnpActivity('4m', 1, 'interacao', 'Troca de sons', 'Quando o bebê vocalizar, responda com sorriso e a mesma “conversa”. Ele aprende que a vez dele também importa.'),
  dnpActivity('4m', 2, 'brincadeira', 'Explorar com segurança', 'Ofereça um tapete firme e brinquedos seguros para pegar, chutar e olhar.'),
  dnpActivity('4m', 3, 'brincadeira', 'Explorar com a boca', 'Bebês conhecem o mundo levando objetos à boca. Ofereça só o que não seja pontiagudo, quente ou pequeno o bastante para engasgar.'),
  dnpActivity('4m', 4, 'interacao', 'Fale, leia e cante', 'A voz da família ajuda o bebê a reconhecer palavras mais adiante.'),
  dnpActivity('4m', 5, 'telas', 'Tela só para ver quem ama', 'Para menores de 2 anos, a orientação da cartilha é evitar telas, salvo chamadas de vídeo com pessoas queridas.', ['screen-time-review']),
  dnpActivity('4m', 6, 'alimentacao', 'Ainda só leite', 'Leite materno ou fórmula continua sendo o alimento desta idade. Outros alimentos, água e sucos ainda não entram.', ['feeding-review']),
  dnpActivity('4m', 7, 'brincadeira', 'Brinquedos fáceis de segurar', 'Chocalhos e livros de pano com figuras grandes costumam funcionar bem.'),
  dnpActivity('4m', 8, 'movimento', 'Tempo para se mexer', 'Evite deixar o bebê por longos períodos em cadeirinha, carrinho ou balanço.'),
  dnpActivity('4m', 9, 'rotina', 'Sono e alimentação no mesmo ritmo', 'Rotinas previsíveis trazem segurança.'),
  dnpActivity('4m', 10, 'brincadeira', 'Acompanhar o brinquedo com o olhar', 'De costas, mostre um objeto colorido e mova-o devagar para os lados e para cima e para baixo.'),
  dnpActivity('4m', 11, 'movimento', 'Movimentar braços e pernas com suavidade', 'Enquanto conversa ou canta, dobre e estique devagar braços e pernas por alguns minutos.'),

  dnpActivity('6m', 1, 'interacao', 'Brincadeira de vai e volta', 'Se o bebê sorrir, sorria. Se fizer um som, copie. Isso fortalece o convívio.'),
  dnpActivity('6m', 2, 'interacao', 'Olhar figuras juntos', 'Mostre imagens coloridas e fale sobre elas. Se ele balbuciar, responda como se fosse parte da história.'),
  dnpActivity('6m', 3, 'interacao', 'Nomeie o mundo', 'No passeio, aponte e diga o nome de carros, árvores e animais.'),
  dnpActivity('6m', 4, 'interacao', 'Música no dia a dia', 'Cantar e ouvir música ajuda o cérebro a se organizar.'),
  dnpActivity('6m', 5, 'telas', 'Conversar vale mais do que a tela', 'A cartilha não recomenda tela para menores de 2 anos, exceto videochamadas com a família.', ['screen-time-review']),
  dnpActivity('6m', 6, 'interacao', 'Aponte o que ele olha', 'Quando o olhar do bebê parar em algo, nomeie aquele objeto.'),
  dnpActivity('6m', 7, 'movimento', 'Brinquedo um pouco longe', 'De bruços ou de costas, coloque um brinquedo fora do alcance para incentivar o rolamento, sempre com supervisão.'),
  dnpActivity('6m', 8, 'interacao', 'Respeite o humor do momento', 'Se estiver feliz, continue. Se estiver chateado, pause e conforte.'),
  dnpActivity('6m', 9, 'alimentacao', 'Converse sobre alimentos sólidos', 'Pergunte ao pediatra quando e como oferecer comida, e quais alimentos aumentam o risco de engasgo. O leite ainda é a base.', ['feeding-review']),
  dnpActivity('6m', 10, 'alimentacao', 'Fome e “já chega” na colher', 'Abrir a boca, apontar ou se animar pode indicar fome. Empurrar a comida, fechar a boca ou virar o rosto pode indicar saciedade.'),
  dnpActivity('6m', 11, 'comportamento', 'Ajudar o bebê a se acalmar', 'Fale baixo, embale, cante ou ofereça o dedo, a chupeta ou um brinquedo conhecido no colo.'),
  dnpActivity('6m', 12, 'movimento', 'Praticar o sentar com apoio', 'Segure o bebê sentado, deixe-o olhar em volta e ofereça um brinquedo enquanto ele busca equilíbrio.'),

  dnpActivity('9m', 1, 'interacao', 'Transforme o balbucio em palavra', 'Se ele disser “bobobo”, repita o som e depois ofereça uma palavra, como “bola”.'),
  dnpActivity('9m', 2, 'movimento', 'Brinquedo um pouco além do alcance', 'Coloque o brinquedo no tapete e incentive rolar, arrastar ou engatinhar. Comemore quando ele chegar.'),
  dnpActivity('9m', 3, 'interacao', 'Tchau e outros gestos', 'Acene ao sair e mostre gestos simples para o bebê pedir o que quer antes de falar.'),
  dnpActivity('9m', 4, 'brincadeira', 'Esconde-achou', 'Cubra o rosto com um pano leve e veja se o bebê o tira.'),
  dnpActivity('9m', 5, 'brincadeira', 'Encher e esvaziar', 'Tire blocos de um pote e coloque-os de volta, revezando a vez.'),
  dnpActivity('9m', 6, 'interacao', 'Minha vez, sua vez', 'Passe um brinquedo de um para o outro.'),
  dnpActivity('9m', 7, 'interacao', 'Ler apontando figuras', 'Nomeie o que aparece na página enquanto aponta.'),
  dnpActivity('9m', 8, 'telas', 'Presença no lugar da tela', 'A orientação da cartilha para menores de 2 anos é priorizar conversa e brincadeira reais.', ['screen-time-review']),
  dnpActivity('9m', 9, 'alimentacao', 'Comer com os dedos e copo com água', 'Fale com o pediatra sobre alimentos seguros e risco de engasgo. Sente-se junto, aceite a bagunça e ofereça um pouco de água em copo.', ['feeding-review', 'choking-review']),
  dnpActivity('9m', 10, 'comportamento', 'Diga o que fazer', 'Em vez de “não fique de pé”, tente “agora é hora de sentar”.'),
  dnpActivity('9m', 11, 'alimentacao', 'Novos sabores com paciência', 'Ofereça alimentos amassados, em purê ou bem picados. Pode ser preciso várias tentativas até aceitar.', ['feeding-review']),
  dnpActivity('9m', 12, 'rotina', 'Despedida curta e clara', 'Ao sair, diga tchau com calma em vez de desaparecer. Ao voltar, anuncie: “papai voltou”.'),

  dnpActivity('12m', 1, 'comportamento', 'Mostre o jeito que você espera', 'Se ele puxar o rabo do animal, ensine a acariciar com suavidade e reconheça quando fizer isso.'),
  dnpActivity('12m', 2, 'interacao', 'Narração do cotidiano', 'Fale o que está acontecendo: “mamãe está lavando as mãos”.'),
  dnpActivity('12m', 3, 'interacao', 'Complete o que ele tenta dizer', 'Se disser “ta”, você pode responder: “sim, um caminhão”.'),
  dnpActivity('12m', 4, 'comportamento', 'Redirecione com calma', 'Troque a situação ou ofereça outro brinquedo. Reserve o “não” para o que for perigoso, sem gritar, bater ou fazer um discurso longo.'),
  dnpActivity('12m', 5, 'seguranca', 'Casa mais segura para explorar', 'Afaste objetos cortantes e quebráveis. Trave medicamentos e produtos de limpeza. Tenha o número de emergência à mão.'),
  dnpActivity('12m', 6, 'interacao', 'Responda quando ele apontar para pedir', 'Se apontar o copo, diga: “você quer o copo? Aqui está o seu copo.”'),
  dnpActivity('12m', 7, 'interacao', 'Aponte o que é interessante', 'Mostre o caminhão, o ônibus ou o animal. Isso prepara o apontar para compartilhar interesse.'),
  dnpActivity('12m', 8, 'telas', 'Brincar juntos ainda é o principal', 'A cartilha não recomenda tela para menores de 2 anos, salvo videochamadas.', ['screen-time-review']),
  dnpActivity('12m', 9, 'alimentacao', 'Água e leite; suco com critério', 'A cartilha menciona água, leite materno ou leite comum. Suco não é necessário; se for oferecido, o texto fala em até 100 ml por dia de suco 100%. Evite bebidas açucaradas.', ['juice-review']),
  dnpActivity('12m', 10, 'alimentacao', 'Texturas novas, várias tentativas', 'Continue oferecendo alimentos amassados, em purê ou bem picados, mesmo que a primeira recusa aconteça.'),
  dnpActivity('12m', 11, 'rotina', 'Tempo para um novo cuidador', 'Leve um brinquedo, manta ou pelúcia conhecida para ajudar na adaptação.'),
  dnpActivity('12m', 12, 'brincadeira', 'Fazer barulho com segurança', 'Panelas, potes ou um chocalho viram instrumento. Incentive o bebê a explorar o som.'),

  dnpActivity('15m', 1, 'interacao', 'Amplie a primeira palavra', 'Se ele disser “ba”, responda: “bola, sim, isso é uma bola”.'),
  dnpActivity('15m', 2, 'interacao', 'Espere um som antes de entregar', 'Quando ele apontar, nomeie o objeto e dê alguns segundos. Se fizer um som, reconheça: “sim! Xícara.”'),
  dnpActivity('15m', 3, 'rotina', 'Pequena ajuda no dia a dia', 'Deixe-o trazer o sapato, colocar o lanche na bolsa ou jogar a meia no cesto.'),
  dnpActivity('15m', 4, 'sono', 'Noite mais previsível', 'A cartilha fala em rotina calma — pijama, dentes e 1 ou 2 livros — e menciona 11 a 14 horas de sono no total, incluindo sonecas, entre 1 e 2 anos.', ['sleep-hours-review']),
  dnpActivity('15m', 5, 'brincadeira', 'Para que serve isto?', 'Mostre um chapéu, um livro ou um copo e demonstre o uso. Depois ofereça para ele imitar.'),
  dnpActivity('15m', 6, 'interacao', 'Músicas com gestos', 'Cante canções com movimentos e veja se ele tenta acompanhar alguma ação.'),
  dnpActivity('15m', 7, 'comportamento', 'Dê nome ao sentimento', 'Diga o que você percebe: “você está triste porque não podemos sair, mas não pode bater. Vamos achar uma brincadeira em casa.”'),
  dnpActivity('15m', 8, 'comportamento', 'Birras fazem parte desta idade', 'Cansaço e fome pioram o momento. Distrair pode ajudar; às vezes basta esperar a tempestade passar com segurança.'),
  dnpActivity('15m', 9, 'comportamento', 'Ensine o jeito gentil', 'Mostre o que fazer e reconheça com palavras, abraço ou beijo quando ele acertar.'),
  dnpActivity('15m', 10, 'telas', 'Pessoas no lugar da tela', 'A cartilha segue sem recomendar tela para menores de 2 anos, exceto videochamadas.', ['screen-time-review']),
  dnpActivity('15m', 11, 'brincadeira', 'Torre para derrubar', 'Empilhe blocos e deixe a criança derrubar.'),
  dnpActivity('15m', 12, 'alimentacao', 'Copo sem tampa e colher', 'Praticar beber e comer sozinho é bagunçado e faz parte do aprendizado.'),

  dnpActivity('18m', 1, 'comportamento', 'Mais atenção ao que você quer ver', 'Comente o que deu certo: “olha como você guardou o brinquedo.” Dê menos palco ao que não deseja.'),
  dnpActivity('18m', 2, 'brincadeira', 'Faz de conta simples', 'Ofereça uma colher para “alimentar” o ursinho e revezem as vezes.'),
  dnpActivity('18m', 3, 'interacao', 'Falando de sentimentos dos outros', 'Se outra criança estiver triste, você pode dizer: “ele parece triste. Vamos levar o ursinho.”'),
  dnpActivity('18m', 4, 'interacao', 'Perguntas curtas', 'Pergunte “o que é isso?” para estimular o olhar e a palavra.'),
  dnpActivity('18m', 5, 'alimentacao', 'Copo e colher no prato', 'Continuar treinando copo sem tampa e colher faz parte desta fase.'),
  dnpActivity('18m', 6, 'comportamento', 'Duas escolhas bastam', 'Na hora de vestir, pergunte se prefere a camisa vermelha ou a azul.'),
  dnpActivity('18m', 7, 'rotina', 'Comer à mesa juntos', 'Sentar junto nas refeições e nos lanches ajuda a família a criar um ritmo.'),
  dnpActivity('18m', 8, 'telas', 'Menos tela também para o adulto', 'A cartilha pede para limitar a tela da criança e também a do adulto que está com ela.', ['screen-time-review']),
  dnpActivity('18m', 9, 'rotina', 'Banheiro só quando houver sinais de prontidão', 'A cartilha sugere conversar com o médico ou a escola. Muitas crianças só avançam entre 2 e 3 anos. Forçar cedo pode atrasar o processo.', ['toilet-review']),
  dnpActivity('18m', 10, 'comportamento', 'Birra: segurança e tempo', 'As crises ainda são comuns. Distrair ou esperar com calma costuma ser mais útil do que um sermão longo.'),
  dnpActivity('18m', 11, 'interacao', 'Fale na altura dos olhos', 'Abaixe-se para o rosto da criança ver sua expressão, não só ouvir as palavras.'),
  dnpActivity('18m', 12, 'interacao', 'Nomeando o corpo', 'Aponte e diga: “aqui está o seu nariz, aqui está o meu nariz.”'),

  dnpActivity('24m', 1, 'interacao', 'Devolva a palavra completa', 'Se disser “nana”, você pode perguntar: “você quer mais banana?”'),
  dnpActivity('24m', 2, 'comportamento', 'Ajude na brincadeira com outras crianças', 'Nesta idade ainda é difícil dividir. Mostre como revezar e usar palavras.'),
  dnpActivity('24m', 3, 'rotina', 'Ajudante da refeição', 'Deixe levar o copo plástico ou o guardanapo até a mesa e agradeça a ajuda.'),
  dnpActivity('24m', 4, 'movimento', 'Bola para chutar e rolar', 'Ofereça bolas para chutar, rolar e jogar em espaço seguro.'),
  dnpActivity('24m', 5, 'brincadeira', 'Brinquedos que “fazem algo”', 'Botões e peças que respondem ao toque ensinam causa e efeito.'),
  dnpActivity('24m', 6, 'brincadeira', 'Baú de roupas para fantasiar', 'Sapatos, chapéus e camisas grandes abrem o faz de conta.'),
  dnpActivity('24m', 7, 'alimentacao', 'A família oferece, a criança decide o quanto', 'O papel do adulto é oferecer comida saudável; o da criança é comer o que conseguir naquele momento.', ['feeding-review']),
  dnpActivity('24m', 8, 'sono', 'Rito noturno estável', 'A cartilha menciona 11 a 14 horas de sono por dia, incluindo sonecas, e uma rotina calma antes de dormir.', ['sleep-hours-review']),
  dnpActivity('24m', 9, 'rotina', 'Treinamento de banheiro sem pressa', 'Confirme com o médico ou a escola se há sinais de prontidão. Começar cedo demais pode gerar estresse.', ['toilet-review']),
  dnpActivity('24m', 10, 'comportamento', 'Elogie o ajudante', 'Convide a guardar brinquedos ou roupas no cesto e reconheça a colaboração.'),
  dnpActivity('24m', 11, 'brincadeira', 'Pronto, preparado, vai', 'No balanço ou em uma corrida curta, faça a contagem e espere o “vai”.'),
  dnpActivity('24m', 12, 'brincadeira', 'Arte simples', 'Giz de cera ou um pouco de tinta no papel. Depois, pendure o desenho onde a criança possa ver.'),

  dnpActivity('30m', 1, 'brincadeira', 'Brincadeira livre', 'Deixe a criança seguir o próprio interesse, experimentar e usar objetos de um jeito novo.'),
  dnpActivity('30m', 2, 'comportamento', 'Nomeie o que deu certo', 'Diga, por exemplo: “gostei de ver você dividindo o brinquedo.”'),
  dnpActivity('30m', 3, 'alimentacao', 'Poucas escolhas saudáveis', 'Ofereça duas ou três opções de lanche ou de roupa.'),
  dnpActivity('30m', 4, 'interacao', 'Perguntas sobre a história', 'Use “quem?”, “o quê?” e “onde?” depois de ler.'),
  dnpActivity('30m', 5, 'interacao', 'Ensaiar brincar junto', 'Mostre como dividir, esperar a vez e usar palavras.'),
  dnpActivity('30m', 6, 'brincadeira', 'Traços e círculos', 'Papel, giz, ou espuma de barbear em uma bandeja. Mostre uma linha e, depois, um círculo para copiar.'),
  dnpActivity('30m', 7, 'interacao', 'Encontro com outras crianças', 'Parque, biblioteca ou um grupo local ajudam a ensaiar amizade.'),
  dnpActivity('30m', 8, 'rotina', 'Refeição em família, sem tela', 'Sempre que possível, o mesmo prato e conversa no lugar da tela.', ['screen-time-review']),
  dnpActivity('30m', 9, 'telas', 'Se houver tela, com adulto por perto', 'A cartilha cita no máximo 1 hora por dia de programa infantil com um adulto presente.', ['screen-time-review']),
  dnpActivity('30m', 10, 'interacao', 'Palavras de comparação', 'Use grande e pequeno, rápido e devagar, dentro e fora.'),
  dnpActivity('30m', 11, 'brincadeira', 'Quebra-cabeça simples', 'Peças de forma, cor ou animal. Nomeie cada uma ao encaixar.'),
  dnpActivity('30m', 12, 'movimento', 'Parque e áreas seguras', 'Subir, correr e gastar energia ao ar livre, com supervisão.'),
  dnpActivity('30m', 13, 'alimentacao', 'Respeitar o apetite do dia', 'Ofereça comida saudável e deixe a criança decidir o quanto come.'),

  dnpActivity('36m', 1, 'comportamento', 'Resolver com apoio, não no lugar', 'Ajude a entender o problema, pensar em uma solução e tentar de novo se precisar.'),
  dnpActivity('36m', 2, 'interacao', 'Palavras para o que sente', 'Nomeie a emoção e ensine um recurso: respirar fundo, abraçar um brinquedo ou ir a um cantinho calmo.'),
  dnpActivity('36m', 3, 'comportamento', 'Poucas regras, bem claras', 'Por exemplo, toque suave na brincadeira. Se quebrar a regra, mostre o que fazer no lugar e reconheça quando acertar.'),
  dnpActivity('36m', 4, 'interacao', 'Perguntas durante a leitura', '“O que está acontecendo na figura?” “O que você acha que vem depois?” Peça um pouco mais de detalhe.'),
  dnpActivity('36m', 5, 'brincadeira', 'Contar o cotidiano', 'Conte degraus, dedos e objetos do dia. Nesta idade a ideia de número começa a se organizar.'),
  dnpActivity('36m', 6, 'interacao', 'Frases um pouco maiores', 'Se disser “quelo nana”, você pode devolver: “eu quero uma banana.”'),
  dnpActivity('36m', 7, 'rotina', 'Ajudante da cozinha', 'Lavar uma fruta ou mexer um ingrediente frio, com supervisão.'),
  dnpActivity('36m', 8, 'rotina', 'Pedidos de 2 ou 3 passos', '“Vá ao quarto, pegue os sapatos e o casaco.”'),
  dnpActivity('36m', 9, 'telas', 'Tela limitada e fora do quarto', 'A cartilha fala em no máximo 1 hora por dia, com adulto, e sem tela no quarto.', ['screen-time-review']),
  dnpActivity('36m', 10, 'interacao', 'Canções e rimas curtas', 'Músicas simples, como uma canção de estrela, cabem no dia a dia.'),
  dnpActivity('36m', 11, 'brincadeira', 'Caixa de desenho', 'Papel, giz de cera e livros para colorir. Façam linhas e formas juntos.'),
  dnpActivity('36m', 12, 'interacao', 'Brincar com outras crianças', 'A convivência ensina amizade e combinados.'),

  dnpActivity('48m', 1, 'rotina', 'Preparar o encontro com o novo', 'Uma história ou uma brincadeira de faz de conta pode deixar um lugar ou uma pessoa nova menos assustadores.'),
  dnpActivity('48m', 2, 'interacao', 'Ler e imaginar o final', 'Pergunte o que está acontecendo e o que pode vir depois.'),
  dnpActivity('48m', 3, 'brincadeira', 'Cores, formas e tamanhos do dia', 'No caminho, pergunte a cor, a forma ou o tamanho do que vocês veem.'),
  dnpActivity('48m', 4, 'comportamento', 'Emprestar as palavras', 'Se ele ainda não souber pedir a vez, ensine: “pode ser a minha vez?”'),
  dnpActivity('48m', 5, 'interacao', 'Cuidar de quem está triste', 'Nomeie o sentimento do outro e sugira um gesto gentil.'),
  dnpActivity('48m', 6, 'comportamento', 'Elogie o comportamento desejado', '“Você está compartilhando esse brinquedo com cuidado.”'),
  dnpActivity('48m', 7, 'comportamento', 'Explique o limite e ofereça outra opção', '“Na cama não dá para pular. Quer ir lá fora ou dançar uma música?”'),
  dnpActivity('48m', 8, 'interacao', 'Outras crianças no parque ou na biblioteca', 'Pergunte sobre grupos e pré-escola da região.'),
  dnpActivity('48m', 9, 'alimentacao', 'Comer junto e dar o exemplo', 'Deixe a criança ver a família comer frutas, legumes, grãos e beber água ou leite.'),
  dnpActivity('48m', 10, 'sono', 'Noite sem tela perto da cama', 'A cartilha sugere evitar tela de 1 a 2 horas antes de dormir, sem aparelho no quarto, e menciona 10 a 13 horas de sono no total.', ['sleep-hours-review', 'screen-time-review']),
  dnpActivity('48m', 11, 'brincadeira', 'Fantasia, panelinha e blocos', 'Entre na brincadeira: prove a “comida” que ela preparou.'),
  dnpActivity('48m', 12, 'interacao', 'Leve a sério o “por quê?”', 'Se não souber a resposta, digam juntos: “não sabemos ainda” e procurem em um livro ou com outro adulto.'),

  dnpActivity('60m', 1, 'comportamento', 'Independência sem alimentar a provocação', 'Nesta idade pode aparecer o “responder”. Dê menos atenção à palavra dura e mais espaço para a criança liderar uma atividade segura. Reconheça quando ela se acalma.'),
  dnpActivity('60m', 2, 'interacao', 'Pergunte sobre a brincadeira', '“Essa ponte ficou interessante. Por que você a colocou aí?”'),
  dnpActivity('60m', 3, 'brincadeira', 'Montar e encaixar', 'Quebra-cabeças e blocos exercitam atenção e planejamento.'),
  dnpActivity('60m', 4, 'interacao', 'Palavras de tempo no cotidiano', 'Fale em hoje, amanhã e ontem. Canções dos dias da semana também ajudam.'),
  dnpActivity('60m', 5, 'rotina', 'Deixar fazer, mesmo imperfeito', 'Arrumar a cama, abotoar ou servir água. Celebre a tentativa e evite “consertar” o que não precisa.'),
  dnpActivity('60m', 6, 'interacao', 'Sentimentos nos livros', 'Nomeie o que os personagens sentem e por quê.'),
  dnpActivity('60m', 7, 'brincadeira', 'Jogo de rimas', 'Pergunte: “o que rima com gato?”'),
  dnpActivity('60m', 8, 'interacao', 'Regras de um jogo simples', 'Um jogo de cartas ou de tabuleiro curto ensina a esperar a vez.'),
  dnpActivity('60m', 9, 'comportamento', 'Um lugar calmo em casa', 'Combine um cantinho seguro para se recompor. Permaneça por perto.'),
  dnpActivity('60m', 10, 'telas', 'Combinado de tela da família', 'A cartilha fala em no máximo 1 hora por dia e sugere um plano de uso de telas da casa.', ['screen-time-review']),
  dnpActivity('60m', 11, 'rotina', 'Refeição conversada', 'O mesmo prato, sem tela, e um papel simples no preparo da comida.'),
  dnpActivity('60m', 12, 'interacao', '“Ler” pelas figuras', 'Peça que conte a história olhando as imagens.'),
  dnpActivity('60m', 13, 'brincadeira', 'Jogos de memória', 'Cartas simples ajudam a sustentar a atenção.')
];

const DNP_REVIEW_NOTES = [
  {
    id: 'not-a-screening-tool',
    title: 'Isto não é triagem padronizada',
    text: 'A lista de marcos da cartilha não substitui uma ferramenta de triagem de desenvolvimento padronizada e validada. Os itens descrevem o que a maioria das crianças (cerca de 75% ou mais) já faz em cada idade.'
  },
  {
    id: 'no-automatic-diagnosis',
    title: 'Sem nota, percentual ou diagnóstico',
    text: 'O aplicativo não calcula normalidade, atraso ou classificação clínica. Um marco não observado, uma preocupação da família ou a perda de uma habilidade devem ser conversados com o médico, sem esperar a próxima etapa.'
  },
  {
    id: 'prematurity-gap',
    title: 'Prematuridade e idade corrigida',
    text: 'O cadastro atual não registra prematuridade nem calcula idade corrigida. A etapa de referência usa só a idade cronológica. Se a criança nasceu prematura, a família pode registrar isso uma vez nesta área e deve perguntar ao pediatra qual idade usar na conversa clínica. O aplicativo não aplica idade corrigida automaticamente.'
  },
  {
    id: 'screening-calendar-divergence',
    title: 'Lembretes automáticos de triagem não foram implementados',
    text: 'A cartilha, alinhada à Academia Americana de Pediatria, menciona momentos de triagem geral e de autismo em idades como 9, 18, 24 e 30 meses. Referências usadas no Brasil podem divergir sobre calendário e instrumentos. Por isso esta versão não cria datas automáticas de triagem geral ou de autismo e mantém a área de triagens formais separada.'
  },
  {
    id: 'cdc-roll-correction',
    title: 'Rolamento aos 6 meses',
    text: 'O marco de 6 meses foi registrado como virar de barriga para baixo para barriga para cima, conforme o CDC atual. A cartilha em português apresenta a direção inversa. Pendente de revisão médica antes de tratar o texto como definitivo no app.'
  },
  {
    id: 'safety-stringing',
    title: 'Alinhavo aos 3 anos',
    text: 'A atividade de passar peças em um cordão foi redigida com peças grandes, adequadas à idade, e supervisão contínua, para reduzir risco de engasgo.'
  },
  {
    id: 'content-adaptation',
    title: 'Redação própria, sentido da cartilha',
    text: 'Os textos foram reescritos para famílias e não reproduzem ilustrações, logotipos ou blocos extensos da cartilha SBP/CDC. Alimentação, suco, telas, horas de sono, desmame e treinamento de banheiro permanecem como orientação da fonte e pedem revisão médica antes de serem tratados como regra atual do app.'
  }
];

const DNP_CATALOG = {
  version: DNP_CATALOG_VERSION,
  areas: DNP_AREAS,
  stages: DNP_STAGES,
  milestones: DNP_MILESTONES,
  activities: DNP_ACTIVITIES,
  expectedCounts: DNP_EXPECTED_COUNTS,
  statuses: DNP_STATUS,
  reviewNotes: DNP_REVIEW_NOTES
};

if (typeof window !== 'undefined') window.DNP_CATALOG = DNP_CATALOG;
if (typeof module !== 'undefined' && module.exports) module.exports = DNP_CATALOG;
